name: Build and publish documentation
on:
  create:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Doxygen
        uses: docker://doxygen/doxygen:latest

      - name: Generate documentation
        run: doxygen Doxyfile

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./html
